---
  ## Instalación de Spectrum v10.4 
  ## Inicialmente se programa para instalarce en Red Hat 7.9 (pruebas satisfactorias)
  ## Autor: Jorge Zavala Navarro

- name: INSTALAR SPECTRUM 10.4 EN LINUX RED HAT 7.9 ENTERPRISE (1143)
  hosts: all
  gather_facts: yes


  ## Definición de las variables correspondientes en el còdigo
  ## path_media_install       --> Ruta donde se encuentra la carpeta de los archivos de instalación
  ## path_media_install_dir   --> Ruta de la carpeta donde se encuentran los arfchivos de instalación
  ## path_media_install_file  --> Ruta en donde se encuentra el archivo de instalación tar.gz
  ## path_sradmin             --> Ruta en donde se va a instalar el SRAdmin
  ## path_install_libs_sh     --> Nombre y ruta del archivo que va a instalar todas las librerias requeridas 
  ## url_repogit              --> URL del repositorio GIT de donde se van a descargar los archivos para la inst.
  ## path_repogit_dir         --> Ruta en donde se van a descargar los archivo desde el repositorio Git
  ## path_repogit_file        --> Nombre yu ruta del archivo que se va a recibir desde el git
  ## user_owner               --> Cuenta de Usuario Owner de la instalaciòn (debe de coincidir con el hii)
  ##
  ## Variables que se esperan desde la ejecución po rel A-Tower
  ## hostname_name            --> Nombre del Hostname
  ## hostname_pretty          --> Nombre descriptivo del hostname
  ## redhat_user              --> Cuenta de usuario de Red Hat    : en caso de que se necesite
  ## redhat_pass              --> Password del usuario en redhat  : en caso de que se necesite
  ## host_user                --> Cuenta de usuario del host origen
  ## host_pass                --> Contraseña del host origen
  ## host_name                --> Nombre del host de donde vamos a extraer el instalabre correspondiente
  ## host_path                --> Nombre y ruta del archivo origen a copiar al destino
  ## flag_suscribir           --> Bandera que nos indica si se suscribe el equipo a la cuenta de redhat (SI/NO)
  ## user_owner               --> Cuenta de Usuario Owner de la instalaciòn (debe de coincidir con el hii)

  vars:
          repo_tag: spestrum_10_4

          vars:
          path_media_install: /home/Spectrum
          path_media_install_dir: /home/Spectrum/SpectrumInstall_10.4_Linux
          path_media_install_file: /root/SpectrumInstall_10.4_Linux.tar.gz
          path_sradmin: /sw/SPECTRUM/SRAdmin
          url_repogit: https://github.com/jzavala74mz/ATower.InstallSpectrum.V10.4
          path_repogit_dir: /home/Spectrum/git
          path_repogit_file: /home/Spectrum/git/ATower.InstallSpectrum.V10.4.zip
          path_install_libs_sh: '{{ path_repogit_dir }}/InstallLibs.sh'
          

  tasks:
          ####################################################
          ##  Obtener la información del sistema operativo  ##
          ####################################################
          - name: Distribución
            debug: "msg='{{ ansible_distribution }}'"

          - name: Distribution version
            debug: "msg='{{ ansible_distribution_version}}'"

          - name: Distribution major version
            debug: "msg='{{ ansible_distribution_major_version }}'"

          #############################
          ##  Condiciones Iniciales  ##
          #############################

          - name: Configurar el modo pemisivo para SELinux
            command: setenforce 0

          - name: 'Configurar el modo permisivo SED y asignar el hostname: {{ hostname_name }}'
            command: sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config

          - name: 'Asignar el hostname {{ hostname_name }}'
            command: hostnamectl set-hostname '{{ hostname_name }}'

          - name: Suscribir la máquina virtual a la cuenta de Red Hat correspondiente
            command: subscription-manager register --username '{{ redhat_user }}' --password '{{ redhat_pass }}' --force
            when: ansible_facts['os_family'] == "RedHat" and flag_suscribir == "SI"

          - name: Actualización automática de las librerias
            command: subscription-manager attach --auto
            when: ansible_facts['os_family'] == "RedHat" and flag_suscribir == "SI"

          ###################################################################
          ##  Descargamos los elementos del repositorio git para instalar  ##
          ###################################################################

          - name: Validar si ya se encuentra instalado el git validando el servicio
            service_facts:
          - debug:
                  msg: Git installed!
            when: "'git' in services"

          - name: Instalar la aplicación git para poder recuperar los recursos correspondientes
            dnf:
                    name: git
                    state: latest
            when: not "'git' in services"

          - name: Validar si existe la carpeta con la información del proyecto contenido en el git
            stat:
                    path: '{{ path_repogit_dir }}'
            register: existe_ruta_carpeta_repogit

          - name: Eliminar la carpeta con el contenido del proyecto en el git para recibir la ultima version
            file:
                    path: '{{ path_repogit_dir }}'
                    state: absent
            when: existe_ruta_carpeta_repogit.stat.exists


          - name: Descargar los recursos del git para este proyecto
            git:
                    repo: https://github.com/jzavala74mz/ATower.InstallSpectrum.V10.4
                    dest: '{{ path_repogit_dir }}'
                    archive: '{{ path_repogit_file }}'


          ##################################################
          ##  Preparar los requerimientos de instalación  ##
          ##################################################
          
          - name: Realizamos la actualización del sistema
            yum:
                    name: "*"
                    state: latest
            ## command: yum update -y

          - name: 'Proporcionar los permisos al archivo {{ path_install_libs_sh }} para que se pueda ejecutar'
            command: 'chmod u+x {{ path_install_libs_sh }}'

          - name: 'Instalar los paquetes requeridos ejecutando el programa en {{ path_install_libs_sh }}'
            shell: '{{ path_install_libs_sh }} > {{ path_install_libs_sh }}.output'


          - name: Instalar el paquete de mlocate
            yum:
                    name: mlocate
                    state: latest

          - name: Actualizar la updatedb
            command: updatedb

          - name: Instalar el paquete ksh
            yum:
                    name: ksh
                    state: latest

          - name: Instalar el paquete libXm.so.4 
            yum:
                    name: libXm.so.4
                    state: latest
   
          - name: Instalar el paquete motif
            yum:
                    name: motif
                    state: latest
                    skip_broken: yes

          - name: Instalar el paquete libXm.so.4
            yum:
                    name: motif-devel 
                    state: latest

                    ## - name: Validar los paquetes instalados para la instalación de Spectrum
                    ## shell: '{{ path_install_libs_sh }} >> {{ path_install_libs_sh }}.output'


          #######################################################
          ##  Adquirir el archivo con la media de instalación  ##
          #######################################################

            
          ## Parámetros a utilizar
          ## host_user   : Cuenta de usuario para conectarse al host
          ## host_pass   : Clave secreta para conectarce 
          ## host_name   : Nombre del servidor origen de donde se va a extraer el archivo de instalación
          ## host_path   : Nombre y ruta del instalable en el servidor origen (podria ser el mismo de tower)
          ## path_media_install_file  : Nombre y ruta del instalador en el servidor destino
          ## path_media_install_dir   : Ruta de la carpeta en donde se encuentran los archivos de instalación
          ## - name: Copiar el archivo con la media de instalación al servidor destimo
          ##   command: 'scp {{ host_user }}@{{ host_name }}:{{ host_path }} {{ path_media_install_file }}'

          - name: Crear la carpeta en donde vamos a despositar el contenido del archivo
            file:
                    path: '{{ path_media_install_dir }}'
                    state: directory
                    mode: '0755'
           
          - name: Transfiriendo archivo de instalación
            command: 'expect {{ path_repogit_dir }}/ScriptCopyinstalador.sh'

            ##copy:
            ##        src: /home/jzavala74mz/Uploads/SpectrumInstall_10.4_Linux.tar.gz
            ##        dest: '{{ path_media_install_file }}'
            ##        remote_src: no


          - name: Descomprimir archivo de instalación
            command: 'tar -zxvf {{ path_media_install_file }} -C {{ path_media_install_dir }}'



          ###############################
          ##  Instalación del SRAdmin  ##
          ###############################

          - name: Crear carpeta para instalar el SRAdmin validado
            file:
                    path: '{{ path_sradmin }}'
                    state: directory
                    mode: '0755'

          - name: Copiar el programa sradmin.exe desde el instalador validar
            copy:
                    src: '{{ path_media_install_dir }}/sdic/linux/sradmin.exe'
                    dest: '{{ path_sradmin }}/sradmin.exe'
                    remote_src: yes
                    backup: no

          - name: Copiar el archivo sradmin.rc2 
            copy:
                    src: '{{ path_media_install_dir }}/sdic/linux/sradmin.rc2'
                    dest: /etc/init.d/sradmin
                    remote_src: yes
                    mode: '500'
                    backup: no

          - name: Chequeo de confirmación
            command: /sbin/chkconfig --add sradmin

          - name: Iniciar servicio de SRAdmin
            command: /etc/init.d/sradmin start 

          - pause:
                  seconds: 10

          - name: Validar el servicio del SRAdmin
            command: /etc/init.d/sradmin status

          - name: Validar la existencia del grupo wheel
            group:
                    name: wheel
                    state: present
                 
          - name: 'Agregar nuestro usuario Owner al grupo Wheel para otorgar permisos {{ user_owner }}'
            command: 'usermod -aG wheel {{ user_owner }}'

          - name: Ejecutar el proceso de Instalaciòn para spectrum (se aceptará la licencia)
            command: '{{ path_media_install_dir }}/sdic/sdiclinux.exe -h {{ path_repogit_dir }}/InstallInfoServer.hii -p {{ path_repogit_dir }}/InstallPassword.txt -accept'


          ########################################
          ##  Levanzar el servicio de Spectrum  ##
          ########################################
          
            ## - name: Colocar en el directorio de comandos
            ## command: chdir=/usr/Spectrum/bin ls

            
          - name: Levantar el servicio de spectrum usando el programa 
            command: /usr/Spectrum/bin/startSS.pl
            become: yes
            become_user: jzavala74mz

          
