- name: restaurar información en la base de datos de spectrum
  hosts: SpectrumDemo
  gather_facts: yes


  vars:
          repo_tag: spestrum_10_4

          vars:
          path_media_install: /home/Spectrum
          path_media_install_dir: /home/Spectrum/SpectrumInstall_10.4_Linux
          path_media_install_file: /root/SpectrumInstall_10.4_Linux.tar.gz
          path_sradmin: /sw/SPECTRUM/SRAdmin
          url_repogit: https://github.com/jzavala74mz/ATower.InstallSpectrum.V10.4
          path_repogit_dir: /home/Spectrum/git
          path_repogit_file: /home/Spectrum/git/ATower.InstallSpectrum.V10.4.zip
          path_install_libs_sh: '{{ path_repogit_dir }}/InstallLibs.sh'
          path_spectrum_root: /usr/Spectrum
          cmd_comando_iniciar_cargar: /SS-Tools/SSdbload -i -l
          cmd_comando_cargar: /SS-Tools/SSdbload -l
          flag_restaurar: SI


  tasks:


          ##############################################################################
          ## Restaurar Spectrum de algun backup especificado en caso de ser requerido ##
          ##############################################################################

          ## expect /home/Spectrum/git/ScriptCopyBackup.sh'

          - name: Transfiriendo archivo de recuperación
            command: 'expect {{ path_repogit_dir }}/ScriptCopyBackup.sh'
            when: flag_restaurar == "SI"

          - name: Validar Transferencia de archivo
            stat:
                    path: /root/salida.xml
            register: stat_existe_respaldo
            when: flag_restaurar == "SI"

          - name: Ubicar en la carpeta de las herramientas SS-Tools
            command: cd /usr/Spectrum/SS-Tools/
            when: flag_restaurar == "SI"

          - name: Restaurar Topologia
            command: '{{ path_spectrum_root }}/SS-Tools//modelinggateway -vnm spectrum -user jzavala74mz -i /root/salida.xml'
            when:  flag_restaurar == "NO"

          - name: Dar permisos al archivo que se va a enviar
            command: chmod 777 /root/salida.xml
            when:  flag_restaurar == "SI"

          - name: Notificando el proceso terminado
            mail:
                    host: mail.werosoft.com.mx
                    port: 587
                    username: jorge.zavala@werosoft.com.mx
                    password: Jorge.Zavala$1974
                    subtype: html
                    from: jorge.zavala@werosoft.com.mx
                    to: 
                            - jzavala74mz@yahoo.com.mx
                            - jzavala74mz@gmail.com
                            - jzavala@werosoft.com.mx
                    cc:
                            - mariana.mendez.piro
                    attach:
                            - /home/jzavala74mz/Uploads/salida.xml
                    subject: A-Tower Instalación de SPECTRUM OK
                    body: 'BUENAS TARDES.<br><br>Informamos que la instalación de Spectrum se ejectó <b>satisfactoriamente</b>. <br><br><br>Saludos'
            delegate_to: localhost
            when:  flag_restaurar == "SI"
            

